### ISSUE TITLE
"Required technology does not exist: ${name}"

### ISSUE THREAD

**Issue by jenslys** [Kikobeats/simple-wappalyzer#72]
Started a fresh project, installed all dep and copied the code straight from the readme, i just get this error:

```node

/Users/jenslys/Kode/wap/node_modules/wappalyzer-core/wappalyzer.js:432
            throw new Error(`Required technology does not exist: ${name}`)
            ^

Error: Required technology does not exist: WordpPress
    at /Users/jenslys/Kode/wap/node_modules/wappalyzer-core/wappalyzer.js:432:19
    at Array.forEach (<anonymous>)
    at /Users/jenslys/Kode/wap/node_modules/wappalyzer-core/wappalyzer.js:430:29
    at Array.forEach (<anonymous>)
    at Object.setTechnologies (/Users/jenslys/Kode/wap/node_modules/wappalyzer-core/wappalyzer.js:429:8)
    at Object.<anonymous> (/Users/jenslys/Kode/wap/node_modules/simple-wappalyzer/src/index.js:13:12)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)

Node.js v20.10.0
```

code:

```js
const wappalyzer = require('simple-wappalyzer')
const getHTML = require('html-get')

getHTML('https://kikobeats.com', { getBrowserless: require('browserless') })
  .then(({ url, html, statusCode, headers }) =>
    wappalyzer({ url, html, statusCode, headers })
  )
  .then(result => console.log(result))

```

**Comment by Kikobeats** [comment]
It seems a bug in the upstream, I send a PR: https://github.com/enthec/webappanalyzer/pull/146
